### ISSUE TITLE
Provide "Quick Started" guide on tc.org home page for both 5.0 server and 4.3 server

### ISSUE THREAD

**Issue by jhouserizer** [Terracotta-OSS/terracotta.org-site#10]
Similar to how ehcache.org site has selectable quick start on home page for Ehcach 3.x and Ehcache 2.x

**Comment by fossf** [comment]
See ehcache.org home page for formatting.

**Comment by fossf** [comment]
http://terracotta.org/documentation/4.1/bigmemorymax/quick-start

**Comment by fossf** [comment]
http://www.ehcache.org/documentation/3.1/clustered-cache.html - for 5.0 quick start info
