### ISSUE TITLE
Fix "software ag" branding on (new) terracotta.org and ehache.org

### ISSUE THREAD

**Issue by jhouserizer** [Terracotta-OSS/terracotta.org-site#6]
Add current "Software AG" logo/branding to site home pages.   E.g.   "by Software AG"

**Comment by fossf** [comment]
Do we have the graphics for this?

**Comment by boyusun** [comment]
Do we need to completely change the theme, or only the logos?

**Comment by boyusun** [comment]
I can work on this, can someone assign this to me? (I couldn't assign it to myself)

**Comment by jhouserizer** [comment]
No, we don't need to change all the theme.

**Comment by boyusun** [comment]
Ok, got it

**Comment by fossf** [comment]
also quartz-scheduler.org

**Comment by boyusun** [comment]
I added the SAG logo in the same way, for all 3 product sites: 
1. https://github.com/Terracotta-OSS/terracotta.org-site/pull/13
2. https://github.com/ehcache/ehcache.org-site/pull/90
3. https://github.com/quartz-scheduler/quartz-scheduler.org-site/pull/9
